name: physiomobile_technical_assessment
description: "A technical assessment app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  email_validator: ^3.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/illustrations/
